### PR TITLE
Fixed ifelse in myquote environment

### PR DESCRIPTION
**Pull request by bmetherall**
When I included the quote I got the error
```
! Undefined control sequence.
<inserted text> \isempty
```
I've modified the quote environment to use ```\ifx``` instead of ```\ifthenelse``` and ```\isempty```. The problem seems to be fixed now.

### CODE REVIEW

**Comment by oliversheridanmethven** [comment]
Please provide a MWE demonstrating the problem first and explain how your solution fixes this. Without a demo showing what this fixes I can't pull this yet.

 Oliver 

 -------- Original Message --------
 Subject: [oliversheridanmethven/single_sheet_report] Fixed ifelse in myquote environment (#1)
 From: Brady Metherall 
 To: oliversheridanmethven/single_sheet_report 
 CC: Subscribed 

When I included the quote I got the error
```
! Undefined control sequence.
&lt;inserted text&gt; \isempty
```
I&#39;ve modified the quote environment to use ```\ifx``` instead of ```\ifthenelse``` and ```\isempty```. The problem seems to be fixed now.
You can view, comment on, or merge this pull request online at:

  https://github.com/oliversheridanmethven/single_sheet_report/pull/1

-- Commit Summary --

  * Fixed ifelse in myquote environment

-- File Changes --

    M mwe/mwe.pdf (0)
    M mwe/mwe.tex (7)
    M mwe/preamble.tex (11)

-- Patch Links --

https://github.com/oliversheridanmethven/single_sheet_report/pull/1.patch
https://github.com/oliversheridanmethven/single_sheet_report/pull/1.diff

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/oliversheridanmethven/single_sheet_report/pull/1

**Comment by bmetherall** [comment]
The following results in the error I mentioned.

```
\documentclass[a4paper, 10pt, english, oneside]{extarticle}
\input{preamble}

\author{Oliver\\Sheridan-Methven} 
\title{Some Interesting Project Title} 
\myface{sheridan_face}

\begin{document}
\maketitle

\begin{myquote}[Name]
	\lipsum[1]
\end{myquote}

\end{document}
```

If this in not the correct syntax for the ```myquote``` environment, could you please post a mwe with a quote.

The PR removes the usage of ```\isempty```.

**Comment by oliversheridanmethven** [comment]
I had had a look at it `\isempty` is from the `xifthen` package, which got lost when I migrated the preamble. I have re-included this package as the solution (in 75b994c7a9a1580702596007ecda7c4040ac4652) , so am unsure if I will merge this commit for now as I have pushed an alternative fix. 

Thanks a huge amount though for suggesting a fix, which is something I rarely see.

**Comment by oliversheridanmethven** [comment]
The following now works as expected (I have added some extra lipsum at the start so the quote isn't trying to be centered next to the picture):

```latex
\documentclass[a4paper, 10pt, english, oneside]{extarticle}
\input{preamble}

\author{Oliver\\Sheridan-Methven} 
\title{Some Interesting Project Title} 
\myface{sheridan_face}

\begin{document}
\maketitle 

\lipsum 

\begin{myquote}[Someone important]
\lipsum[1]    
\end{myquote}
\end{document}
```

Which gives:

image

**Pull request closed without merging**
